# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ffccf4abb2318b9332f62c8cd483c62d3c5cc50293f781ad6a59e9a1e909b5c8be92e4ef2668e7e56d85295e5859317ca9755c6c2e5f74972a83cb1bd955be9

test:
  secret_key_base: 436f423f4dce1b123c360e98e912c159b2752e99be2d0de8575b7d308de0bbd3dc00512054cce6e161d98a1b4960bfec268c3d95bff4cad4cd029178f4a2ee36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
